# malice/shadow-server plugin configuration.

name = 'shadow-server'
description = 'shadow-server - Malice ShadowServer Hash Lookup Plugin'
category = 'intel'
version = '0.1.0'

accepts = [ 'hash' ]
hashtypes = [ 'md5', 'sha1' ]

[system]
cpu = 0.5
ram = 256 # MB

[settings]
